spring:
  application:
    name: CounsellorsPortal
  datasource:
    url: jdbc:mysql://9h6yd.h.filess.io:3307/mydatabase_slightcave
    username: mydatabase_slightcave
    password: 7b394eb1376df2e13e95eebea9012599ed58777f
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  main:
    banner-mode: off
server:
  port: 9090